// <auto-generated />
using System;
using FysioEnterprise.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FysioEnterprise.Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FysioEnterprise.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BirthdayDiscountUsedYear")
                        .HasColumnType("int");

                    b.Property<string>("ClientAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ClientBirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClientPrefferedStaffID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientEmail")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("FysioEnterprise.Domain.Entities.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClinicAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicOpeningHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("FysioEnterprise.Domain.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PromotionDiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PromotionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PromotionStartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PromotionName")
                        .IsUnique();

                    b.HasIndex("PromotionStartTime", "PromotionEndTime")
                        .IsUnique();

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("FysioEnterprise.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionClientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionInstanceTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SessionPromotion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionRoomID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionStaffID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("FysioEnterprise.Domain.Entities.SessionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("AllowedAuthorisationNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionTypeMaxAmount")
                        .HasColumnType("int");

                    b.Property<string>("SessionTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("SessionTypeTimeSpan")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("SessionTypes");
                });

            modelBuilder.Entity("FysioEnterprise.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StaffAuthorisationNumber")
                        .HasColumnType("int");

                    b.Property<string>("StaffAuthorisationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffContactInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffLastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("FysioEnterprise.Domain.Entities.Client", b =>
                {
                    b.OwnsOne("FysioEnterprise.Domain.ValueObjects.LoyaltyLevel", "ClientLoyaltyLevel", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("LoyaltyLevelDiscountPercentage")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("LoyaltyLevelName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.Navigation("ClientLoyaltyLevel")
                        .IsRequired();
                });

            modelBuilder.Entity("FysioEnterprise.Domain.Entities.Clinic", b =>
                {
                    b.OwnsMany("FysioEnterprise.Domain.Entities.Room", "ClinicRooms", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ClinicID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("RoomNumber")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ClinicID");

                            b1.ToTable("Room");

                            b1.WithOwner()
                                .HasForeignKey("ClinicID");
                        });

                    b.Navigation("ClinicRooms");
                });

            modelBuilder.Entity("FysioEnterprise.Domain.Entities.Session", b =>
                {
                    b.OwnsOne("FysioEnterprise.Domain.ValueObjects.Price", "priceTotal", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("PriceTotal");

                            b1.HasKey("SessionId");

                            b1.ToTable("Sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.OwnsOne("FysioEnterprise.Domain.ValueObjects.TimeSlot", "SessionTimeSlot", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("From")
                                .HasColumnType("datetime2")
                                .HasColumnName("SessionStartTime");

                            b1.Property<DateTime>("To")
                                .HasColumnType("datetime2")
                                .HasColumnName("SessionEndTime");

                            b1.HasKey("SessionId");

                            b1.ToTable("Sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("SessionTimeSlot")
                        .IsRequired();

                    b.Navigation("priceTotal")
                        .IsRequired();
                });

            modelBuilder.Entity("FysioEnterprise.Domain.Entities.SessionType", b =>
                {
                    b.OwnsOne("FysioEnterprise.Domain.ValueObjects.Price", "SessionTypePrice", b1 =>
                        {
                            b1.Property<Guid>("SessionTypeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("SessionTypePrice");

                            b1.HasKey("SessionTypeId");

                            b1.ToTable("SessionTypes");

                            b1.WithOwner()
                                .HasForeignKey("SessionTypeId");
                        });

                    b.Navigation("SessionTypePrice")
                        .IsRequired();
                });

            modelBuilder.Entity("FysioEnterprise.Domain.Entities.Staff", b =>
                {
                    b.OwnsMany("FysioEnterprise.Domain.ValueObjects.StaffClinicAssignment", "ClinicAssignments", b1 =>
                        {
                            b1.Property<Guid>("StaffId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ClinicId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("StaffId", "ClinicId");

                            b1.ToTable("StaffClinicAssignment");

                            b1.WithOwner()
                                .HasForeignKey("StaffId");
                        });

                    b.Navigation("ClinicAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
